/**
 * Seed list of NSE F&O stock underlyings, used ONLY by the mock/demo provider so it
 * has something realistic to simulate without a live broker connection.
 *
 * This is NOT the source of truth for the real screener: the live provider (e.g. Kite)
 * derives the current F&O universe automatically from the broker's own instrument
 * master on every refresh (see KiteProvider.getOptionInstruments), so additions/removals
 * from NSE's official F&O list are picked up without any code change here.
 */
export const MOCK_FNO_UNDERLYINGS: string[] = [
  "RELIANCE", "TCS", "HDFCBANK", "ICICIBANK", "INFY", "HINDUNILVR", "ITC", "SBIN",
  "BHARTIARTL", "KOTAKBANK", "LT", "AXISBANK", "BAJFINANCE", "ASIANPAINT", "MARUTI",
  "SUNPHARMA", "TITAN", "ULTRACEMCO", "NESTLEIND", "WIPRO", "ADANIENT", "ADANIPORTS",
  "ONGC", "NTPC", "POWERGRID", "M&M", "TATASTEEL", "TATAMOTORS", "JSWSTEEL", "HCLTECH",
  "BAJAJFINSV", "TECHM", "GRASIM", "DRREDDY", "CIPLA", "DIVISLAB", "EICHERMOT",
  "HEROMOTOCO", "BAJAJ-AUTO", "BRITANNIA", "COALINDIA", "HINDALCO", "APOLLOHOSP",
  "SBILIFE", "HDFCLIFE", "INDUSINDBK", "UPL", "BPCL", "IOC", "GAIL", "VEDANTA",
  "PIDILITIND", "DABUR", "GODREJCP", "MARICO", "COLPAL", "BERGEPAINT", "SIEMENS",
  "ABB", "HAVELLS", "VOLTAS", "CROMPTON", "BOSCHLTD", "MOTHERSON", "BALKRISIND",
  "MRF", "APOLLOTYRE", "ASHOKLEY", "TVSMOTOR", "ESCORTS", "SRF", "PIIND", "AARTIIND",
  "DEEPAKNTR", "NAVINFLUOR", "GNFC", "CHAMBLFERT", "COROMANDEL", "GUJGASLTD", "IGL",
  "PETRONET", "GSPL", "CONCOR", "CANBK", "BANKBARODA", "PNB", "UNIONBANK",
  "IDFCFIRSTB", "FEDERALBNK", "RBLBANK", "BANDHANBNK", "AUBANK", "CHOLAFIN",
  "MUTHOOTFIN", "MANAPPURAM", "LICHSGFIN", "PFC", "RECLTD", "IRFC", "SAIL", "NMDC",
  "NATIONALUM", "HINDCOPPER", "JINDALSTEL", "JSWENERGY", "TATAPOWER", "ADANIPOWER",
  "ADANIGREEN", "ADANIENSOL", "TORNTPOWER", "CESC", "NHPC", "SJVN", "IEX", "MCX",
  "BSE", "CDSL", "ANGELONE", "IIFL", "MOTILALOFS", "CAMS", "KFINTECH", "NAUKRI",
  "ZOMATO", "NYKAA", "PAYTM", "POLICYBZR", "DELHIVERY", "IRCTC", "IRCON", "RVNL",
  "RAILTEL", "BEL", "BHEL", "HAL", "BDL", "MAZDOCK", "COCHINSHIP", "GRSE",
  "DATAPATTNS", "ZENTEC", "KAYNES", "DIXON", "AMBER", "POLYCAB", "KEI", "FINCABLES",
  "EXIDEIND", "AMARAJABAT", "SUNDRMFAST", "SCHAEFFLER", "SKFINDIA", "TIMKEN",
  "CUMMINSIND", "THERMAX", "BHARATFORG", "GRAPHITE", "HEG", "RATNAMANI", "JSL",
  "WELCORP", "APLAPOLLO", "SUPREMEIND", "ASTRAL", "FINPIPE", "CERA", "KAJARIACER",
  "HSIL", "CENTURYPLY", "GREENPLY", "ACC", "AMBUJACEM", "SHREECEM", "DALBHARAT",
  "JKCEMENT", "RAMCOCEM", "HEIDELBERG", "INDIACEM", "JKLAKSHMI", "STARCEMENT",
  "LTF", "LTTS", "LTIM", "PERSISTENT", "COFORGE", "MPHASIS", "OFSS", "TATAELXSI",
  "KPITTECH", "SONACOMS", "UNOMINDA", "ENDURANCE", "SUPRAJIT", "GABRIEL",
  "MINDACORP", "JBMA", "IDEA", "INDUSTOWER", "TATACOMM", "GMRAIRPORT", "GLENMARK",
  "LUPIN", "ALKEM", "TORNTPHARM", "ABBOTINDIA", "PFIZER", "SANOFI", "IPCALAB",
];
